plugins:
- yml
overrides:
- files:
  - '*.yml'
  - '*.yaml'
  parser: yaml-eslint-parser
  rules:
    yml/block-mapping: # https://ota-meshi.github.io/eslint-plugin-yml/rules/block-mapping.html
    - WARN
    - singleline: always
      multiline: always
    yml/block-mapping-colon-indicator-newline: WARN # https://ota-meshi.github.io/eslint-plugin-yml/rules/block-mapping-colon-indicator-newline.html
    yml/block-sequence: WARN # https://ota-meshi.github.io/eslint-plugin-yml/rules/block-sequence.html
    yml/block-sequence-hyphen-indicator-newline: # https://ota-meshi.github.io/eslint-plugin-yml/rules/block-sequence-hyphen-indicator-newline.html
    - WARN
    - never
    - nestedHyphen: never
    yml/flow-sequence-bracket-spacing: WARN # https://ota-meshi.github.io/eslint-plugin-yml/rules/flow-sequence-bracket-spacing.html
    yml/indent: # https://ota-meshi.github.io/eslint-plugin-yml/rules/indent.html
    - WARN
    - 2
    - indentBlockSequences: false
    yml/key-spacing: WARN # https://ota-meshi.github.io/eslint-plugin-yml/rules/key-spacing.html
    yml/no-multiple-empty-lines: # https://ota-meshi.github.io/eslint-plugin-yml/rules/no-multiple-empty-lines.html
    - WARN
    - max: 1
      maxBOF: 0
      maxEOF: 1
    yml/no-tab-indent: WARN # https://ota-meshi.github.io/eslint-plugin-yml/rules/no-tab-indent.html
    yml/no-trailing-zeros: WARN # https://ota-meshi.github.io/eslint-plugin-yml/rules/no-trailing-zeros.html
    yml/plain-scalar: WARN # https://ota-meshi.github.io/eslint-plugin-yml/rules/plain-scalar.html
    yml/quotes: # https://ota-meshi.github.io/eslint-plugin-yml/rules/quotes.html
    - WARN
    - prefer: single
      avoidEscape: true
    yml/spaced-comment: WARN # https://ota-meshi.github.io/eslint-plugin-yml/rules/spaced-comment.html
    yml/sort-keys:
    - WARN # https://ota-meshi.github.io/eslint-plugin-yml/rules/sort-keys.html
    - hasProperties:
      - version
      - blocks
      pathPattern: ^$
      order:
      - version
      - palette
      - blocks
      - final_space
      - order:
          type: asc
          natural: true
    - hasProperties:
      - type
      - segments
      pathPattern: ^blocks\[\d+\]$
      order:
      - type
      - alignment
      - newline
      - segments
      - order:
          type: asc
          natural: true
    - hasProperties:
      - type
      - style
      pathPattern: ^blocks\[\d+\]\.segments\[\d+\]$
      order:
      - type
      - alias
      - properties
      - template
      - templates
      - templates_logic
      - interactive
      - style
      - leading_diamond
      - trailing_diamond
      - powerline_symbol
      - foreground
      - foreground_templates
      - background
      - background_templates
      - order:
          type: asc
          natural: true
    - pathPattern: ^blocks\[\d+\]\.segments\[\d+\]\.properties\.mapped_shell_names$
      order:
      - order:
          type: asc
          natural: true
